name: best_rent
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  geolocator: ^11.0.0
  google_maps_places_autocomplete_widgets: ^1.2.2
  envied: ^0.5.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  geocoding: ^3.0.0
  google_geocoding_api: ^1.4.1
  calendar_date_picker2: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  envied_generator: ^0.5.3
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
